
services:

  postgres:
    image: postgres:15
    container_name: inventory_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl_pipeline:
    build: .
    container_name: inventory_etl
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: inventory_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app

volumes:
  postgres_data: